package ca.gc.cyber.assemblyline.java.client.model.submission;

import lombok.*;
import lombok.experimental.SuperBuilder;
import lombok.extern.jackson.Jacksonized;

import java.util.List;
import java.util.Map;

@Data
// Hide setters that would otherwise be generated by @Data
@Setter(AccessLevel.NONE)
@Jacksonized
@SuperBuilder
@AllArgsConstructor
public class SubmissionBase {

    /**
     * List of files that were originally submitted
     */
    private List<File> files;
    /**
     * Submission ID
     */
    private String sid;
    /**
     * Submission parameters
     */
    private SubmissionParams params;
    /**
     * Metadata associated to the submission
     */
    private Map<String, Object> metadata;


    @Value
    @Builder
    public static class File {
        /**
         * Name of the file
         */
        String name;
        /**
         * SHA256 hash of the file
         */
        String sha256;
        /**
         * Size of the file
         */
        long size;
    }
}
